version: "3.4"

networks:
  interviewer-network:
    driver: bridge

services:
  frontend:
    container_name: interviewer-spa
    image: interviewer-spa-image
    restart: never
    build:
      context: .
      dockerfile: Dockerfile_local
    ports:
      - 4200:80
    networks:
      - interviewer-network
